policy:
  enabled: true
  policies:
  - kind: policy
    name: octocat
    match:
      repo:
      - "octocat/*"
      - "octocat/hello-world"
    metadata:
      namespace: octocat
    resources:
      request:
        cpu: 1000
        memory: 512MiB
      limit:
        cpu: 4000
        memory: 1GiB
    node_selector:
      disktype: ssd
  - kind: policy
    name: default
    metadata:
      namespace: default
