{{- if .Values.rbac.enabled -}}
{{- $root := . -}}
{{- range $nsName := .Values.rbac.buildNamespaces -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "drone-runner-kube.fullname" $root }}
  namespace: {{ . | quote }}
  labels:
    {{- include "drone-runner-kube.labels" $root | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "drone-runner-kube.fullname" $root }}
    namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "drone-runner-kube.fullname" $root }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
