{{- $fullName := include "drone-runner-kube.fullname" . -}}
{{- $namespace := .Release.Namespace -}}
{{- with .Values.env.secret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
