{{- with .Values.env.secret }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "drone-runner-kube.fullname" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
