{{- $fullName := include "drone-server.fullname" . -}}
{{- $namespace := .Release.Namespace -}}
{{- with .Values.env.configMap }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
