{{- $fullName := include "drone-server.fullname" . -}}
{{- with .Values.env.configMap }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
