{{- $fullName := include "drone-server.fullname" . -}}
{{- with .Values.env.secret }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
