apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drone-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "drone-server.selectorLabels" . | nindent 4 }}
